"""user-post relation

Revision ID: 3b978ffb65e0
Revises: b8a88c241e12
Create Date: 2025-11-16 10:05:51.589553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b978ffb65e0'
down_revision = 'b8a88c241e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_posts_user_id_users", 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint("fk_posts_user_id_users", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
