"""Add SportEvent and SportType models

Revision ID: 9c2b36a36ce1
Revises: b03b7ee1ad09
Create Date: 2025-11-30 19:38:48.851958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2b36a36ce1'
down_revision = 'b03b7ee1ad09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sport_types')),
    sa.UniqueConstraint('name', name=op.f('uq_sport_types_name'))
    )
    op.create_table('sport_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sport_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sport_types.id'], name=op.f('fk_sport_events_sport_type_id_sport_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sport_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sport_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_events')
    op.drop_table('sport_types')
    # ### end Alembic commands ###
